### ISSUE TITLE
Support publish-composite

### ISSUE THREAD

**Issue by rgnevashev** [johanbrook/meteor-publication-collector#11] opened 2016-10-27 09:26 UTC

**Comment by ShinyLeee** [comment] 2017-01-09 13:09
@johanbrook 
I got test failure without report when I test publish-composite function.
![image](https://cloud.githubusercontent.com/assets/13724426/21767465/577f1622-d6af-11e6-86c1-0c45eb3c1be4.png)

But why in [meteor/todos](https://github.com/meteor/todos/blob/master/imports/api/todos/todos.tests.js#L55), the publish-composite function can test well?

I checked the package version, meteor/todos got publication-collector@0.0.1, and in my project it was johanbrook:publication-collector@1.0.5. But why the older package can test well?

**Comment by johanbrook** [comment] 2017-01-09 13:35
Hm, not sure why they use an older version (https://github.com/meteor/todos/blob/master/.meteor/packages#L73).

Perhaps some recent version of this package broke publish-composite.

**Comment by workflow** [comment] 2017-01-26 21:25
@ShinyLeee I'm using the latest versions of both packages, and it works fine here!

If you provide us with a reproduction, I'm happy to see if I can help.

**Comment by ShinyLeee** [comment] 2017-01-27 05:55
@workflow 
Thanks for your kindness,[here is reproduction](https://github.com/ShinyLeee/meteor-publication-collector-repro).

**Comment by workflow** [comment] 2017-01-27 11:38
@ShinyLeee Hmm your repro isn't failing at my end it seems!

![screenshot9](https://cloud.githubusercontent.com/assets/1276854/22369521/8fbd1170-e48c-11e6-8c34-bdf4f9c46a6c.png)

This is on Ubuntu 14.04.

I noted some contradictory error logs here:

```
I20170127-12:34:43.279(1)? MochaRunner.runServerTests: Starting server side tests with run id ZF6w9b9pbeT6jzEhw
W20170127-12:34:43.743(1)? (STDERR) MochaRunner.runServerTests: failures: 1
I20170127-12:35:34.723(1)? MochaRunner.runServerTests: Starting server side tests with run id LmuGAjtqKrtXnG9XN
W20170127-12:35:34.762(1)? (STDERR) MochaRunner.runServerTests: failures: 0
I20170127-12:35:35.695(1)? MochaRunner.runServerTests: Starting server side tests with run id EzWiCWiJ97mSXrNX2
W20170127-12:35:35.758(1)? (STDERR) MochaRunner.runServerTests: failures: 1
```

but from the browser output, the tests seem to be passing.

I never triedy `practicalmeteor:mocha` as a test driver before, let me know if I'm missing something here.

**Comment by ShinyLeee** [comment] 2017-01-28 07:03
Yeah, the problem is terminal got failure, but browser not show it.
Can u tell me which test driver package used in your project?

**Comment by workflow** [comment] 2017-01-29 13:22
@ShinyLeee I am currently using `dispatch:mocha`, since running only server-side tests.

meteor/todos is using `dispatch:mocha-phantomjs`

**Comment by ShinyLeee** [comment] 2017-01-30 03:39
@workflow After use dispatch:mocha package, I have found specific error message in console.The error show `done() called multiple times`.
![image](https://cloud.githubusercontent.com/assets/13724426/22411597/8abcfc02-e6e0-11e6-88c4-3ee60c9f98d6.png)

**Comment by workflow** [comment] 2017-02-02 13:22
@ShinyLeee Thank you for reporting and following up!

Apart from #16, everything else seems to work fine with `publish-composite`, at least on my end. Would you agree that this issue can therefore be closed?

**Comment by rgnevashev** [comment] 2017-02-12 22:59
this is workingwith publishComposite, you can close ticket.

**Comment by ShinyLeee** [comment] 2017-02-13 02:41
Yeah！Work fine after 1.0.6. You can close it.

**Closed** 2017-02-13 10:04 UTC
Labels: help wanted
