### ISSUE TITLE
Not working with `peerlibrary:reactive-publish`

### ISSUE THREAD

**Issue by jaqua** [johanbrook/meteor-publication-collector#21] opened 2017-02-25 20:13 UTC
I can't use `publication-collector` while using `peerlibrary:reactive-publish` at the same time.

**server/example.test.js**

	import { PublicationCollector } from 'meteor/johanbrook:publication-collector'
	import '/imports/api/server/publications.js'

	describe('example', () => {
		it('should return empty array', function(done) {
			const collector = new PublicationCollector()

			collector.collect('publication', (collections) => {
				expect(collections.publication).to.be.deep.equal([])
				done()
			})
		})
	})

**server/publications.js**

	Meteor.publish('publication', function() {
		this.autorun(function() {
			return Collection.find({ any: 'thing' })
		})
	})

I have to remove `this.autorun()` to get the test working. Otherwise I'll get this error:

	Error: publish._isDeactivated is not a function
    at Computation.<anonymous> (packages/peerlibrary_reactive-publish.js:349:24)
    at runWithEnvironment (packages/meteor.js:1176:24)
    at packages/meteor.js:1189:14
    at packages/peerlibrary_server-autorun.js:469:23
    at packages/peerlibrary_server-autorun.js:447:18
    at Function.FiberUtils.synchronize (packages/peerlibrary_fiber-utils.js:183:12)
    at Computation.Tracker.Computation.Computation._runInside (packages/peerlibrary_server-autorun.js:436:23)
    at packages/peerlibrary_server-autorun.js:461:22
    at Function.FiberUtils.synchronize (packages/peerlibrary_fiber-utils.js:183:12)
    at Computation.Tracker.Computation.Computation._compute (packages/peerlibrary_server-autorun.js:458:23)

Using: 
- johanbrook:publication-collector@1.0.6
- peerlibrary:reactive-publish@0.3.0
- METEOR@1.4.2.6

**Comment by johanbrook** [comment] 2017-02-27 10:05
Dupe of https://github.com/johanbrook/meteor-publication-collector/issues/20.

**Closed by johanbrook** 2017-02-27 10:05 UTC
